### ISSUE TITLE
SyntaxError: invalid syntax during import

### ISSUE THREAD

**Issue by Guangyou** [mtien/PeptideBuilder#2]
I am trying PeptideBuilder, but an error appears during import Geometry. It shows:

    print "Input Rotamers List: not long enough"
                                               ^
SyntaxError: invalid syntax.

My local python version is 3.4.

**Comment by mtien** [comment]
This was made in python 2.7.

If you consult this page https://docs.python.org/3/whatsnew/3.0.html you will see that "print" has now become a function and requires parenthesis. Someone has gladly converted all these print statements https://github.com/mchelem/peptide

Hope this helps.
MZ Tien

**Comment by clauswilke** [comment]
The code should now be fixed to work in python 3.x as well.
