### ISSUE TITLE
pip install peptidebuilder fails.

### ISSUE THREAD

**Issue by ewmoore** [mtien/PeptideBuilder#3]
`pip install peptidebuilder`  fails.  If I include both `--allow-external PeptideBuilder` and `--allow-unverified PeptideBuilder` it still fails.  I'd really rather not have to download this directly from github to use it, let alone trying to explain to others how to get it installed.

I'm thinking this used to work?  However, I don't really remember how I installed this earlier.

**Comment by clauswilke** [comment]
We never put this on pip, because the whole thing is really just two files, `Geometry.py` and `PeptideBuilder.py`. However, we can look into making this available through pip, shouldn't be too much work.

**Comment by ewmoore** [comment]
Please do.  I think my confusion comes from the fact that there is a page on pypi.python.org for the package (I guess to reserve the name?), but it is not installable through pip. 

I'm trying to write some instructions for a colleague who is new to python and I'd rather not get into downloading things from github and adding by hand to site-packages and so on.  And as it looks like there are some changes since I've downloaded it, it might be nice for you to release those as well.

Let me say thanks while I'm here. I've found it to be quite useful. It has made some otherwise irritating things easy to do.

**Comment by clauswilke** [comment]
Yes, pypi lists the package, and me as maintainer. I have no recollection of registering the package with pypi. I presume it was just to reserve the name.

I'm glad you find the code useful.

**Comment by clauswilke** [comment]
Installing through `pip` should now work:
```
~wilke$ pip install peptidebuilder
Downloading/unpacking peptidebuilder
  Downloading PeptideBuilder-1.0.1.tar.gz
  Running setup.py (path:/private/var/folders/q8/wptgtbdn1pz0cfgrz39gq00m0000gn/T/pip_build_wilke/peptidebuilder/setup.py) egg_info for package peptidebuilder
    
Requirement already satisfied (use --upgrade to upgrade): Biopython in /Library/Python/2.7/site-packages (from peptidebuilder)
Installing collected packages: peptidebuilder
  Running setup.py install for peptidebuilder
    
Successfully installed peptidebuilder
Cleaning up...
```

However, the peptidebuilder test suite is not integrated in `setup.py` yet. As of now, tests still need to be run manually.

**Comment by ewmoore** [comment]
Great! Thank you very much.
