### ISSUE TITLE
How to create a peptide model based on an amino acid sequence?

### ISSUE THREAD

**Issue by ewijaya** [mtien/PeptideBuilder#44]
Hi, 

Thank you for making this great package. 
I have this code, which supposes to produce the same identical PDB file with your initial [simpleExample.py](https://github.com/clauswilke/PeptideBuilder/blob/master/examples/simpleExample.py).

It basically takes a string and makes a 3D model out of it.

```
from PeptideBuilder import Geometry
import PeptideBuilder
import Bio.PDB

def split(word):
    return [char for char in word]

wanted_peptide = "GGGGGG"
res = split(wanted_peptide)
geo = Geometry.geometry(res[0])
geo.phi = -60
geo.psi_im1 = -40

structure = PeptideBuilder.initialize_res(geo)
nres = res[1:len(res)]

for r in nres:
    print(r)
    rgeo = Geometry.geometry(r)
    PeptideBuilder.add_residue(structure, rgeo)

PeptideBuilder.add_terminal_OXT(structure)

out = Bio.PDB.PDBIO()
out.set_structure(structure)
out.save("my.example.pdb")
```

But the corresponding output it produces with Pymol is this:

<img width="540" alt="Screen Shot 2021-03-11 at 16 53 56" src="https://user-images.githubusercontent.com/9668738/110754551-4daa3f00-828b-11eb-961a-d5a9896221c4.png">

Whereas with your initial [simpleExample.py](https://github.com/clauswilke/PeptideBuilder/blob/master/examples/simpleExample.py)
it produces this:

<img width="578" alt="Screen Shot 2021-03-11 at 16 53 30" src="https://user-images.githubusercontent.com/9668738/110754271-f3a97980-828a-11eb-9e3d-113236de3061.png">

Why my code doesn't produce identical results?
At the end of the day, I'd like to take an amino acid string like "LKTW" as input and make the model.
How can I approach that?

Ed

**Comment by clauswilke** [comment]
> Why my code doesn't produce identical results?

Because it's different code?

You're not setting backbone angles in your for loop, so you're getting default angles, which (if I remember correctly) correspond to the extended conformation.
